version: "2"
exclude_patterns:
- rasa/core/utils.py   # codeclimate has some encoding issues with this files because of emojis
checks:
  argument-count:
    config:
      threshold: 10
  file-lines:
    enabled: false
  method-count:
    enabled: false
plugins:
  sonar-python:
    enabled: true
    config:
      minimum_severity: critical
  bandit:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
  